// empty

const GET_DOCTORS_DATA_REQUEST = "GET_DOCTORS_DATA_REQUEST";
const GET_DOCTORS_DATA_SUCCESS = "GET_DOCTORS_DATA_SUCCESS";
const GET_DOCTORS_DATA_FAILURE = "GET_DOCTORS_DATA_FAILURE";

export {
  GET_DOCTORS_DATA_REQUEST,
  GET_DOCTORS_DATA_SUCCESS,
  GET_DOCTORS_DATA_FAILURE,
};
