// empty

const GET_DOCTORS_DATA_REQUEST = "GET_DOCTORS_DATA_REQUEST";
const GET_DOCTORS_DATA_SUCCESS = "GET_DOCTORS_DATA_SUCCESS";
const GET_DOCTORS_DATA_FAILURE = "GET_DOCTORS_DATA_FAILURE";

export {
  GET_DOCTORS_DATA_REQUEST,
  GET_DOCTORS_DATA_SUCCESS,
  GET_DOCTORS_DATA_FAILURE,
};

export const GET_SINGLE_DOCTOR_LOADING = "get_single_doctor/loading";
export const GET_SINGLE_DOCTOR_SUCCESS = "get_single_doctor/sucess";
export const GET_SINGLE_DOCTOR_ERROR = "get_single_doctor/error";

export const BOOK_APPOINTMENT_LOADING = "BOOK_APPOINTMENT_LOADING";
export const BOOK_APPOINTMENT_SUCESSS = "BOOK_APPOINTMENT_SUCESSS";
export const BOOK_APPOINTMENT_FAILURE = "BOOK_APPOINTMENT_FAILURE";

export const PATIENT_QUEUE_LENGTH = "PATIENT_QUEUE_LENGTH"